### ISSUE TITLE
[OPTIONAL BUGFIX] Add Y2030 bugfix

### ISSUE THREAD

**Issue by TheSystemGuy1337** [Prakxo/ac-decomp#210] opened 2024-01-06 17:25 UTC
We're 7 years away from the year 2030, and since we're reverse engineering the game now would be a great time to implement a Y2030 fix. Because we need to stop people from capitalizing on it and selling 40-dollar Y2030 survival kits. Nobody has studied the effects, so it could be much like the Y2K problem. We should fix it now while we still have time.

**Comment by Prakxo** [comment] 2024-01-06 17:52
The repo can't currently achieve that yet, since the timein submenú overlay (aka the date changer before loading your player) isn't implemented yet, and other changes in the repo too that clamp the year to 2030

Regardless anything, I think it would be good to do that whenever it's done, but at the moment it's not possible with the decomp at this current state

**Comment by TheSystemGuy1337** [comment] 2024-01-06 18:28
So, we should have this as somewhat of a priority. Besides, we're 7 years away from 2030, so this really isn't an issue right now. We nearly got burned with Y2K, and we might get burned with Y2038. When it becomes possible (hopefully soon within a 7-year period), we should add it. And chances are other Animal Crossing games may share the same mechanism for managing the clock; so, we may be able to fix CF, NL, and NH in one sweep of the rug. Nintendo's programmers should have had foresight. We're doing their job for them

**Comment by MisterSheeple** [comment] 2024-01-06 18:55
I think the main problem is that a lot of things (such as the event calendar) are all hardcoded through 2030. The most ideal way of implementing this would be to go through and create some sort of algorithm for generating the event calendar so that it can go beyond 2030. And since the decomp is still in progress, it's just not possible right now.

**Comment by Cuyler36** [comment] 2024-01-07 04:56
> The repo can't currently achieve that yet, since the timein submenú overlay (aka the date changer before loading your player) isn't implemented yet, and other changes in the repo too that clamp the year to 2030
> 
> Regardless anything, I think it would be good to do that whenever it's done, but at the moment it's not possible with the decomp at this current state

`m_timeIn_ovl` is linked, https://github.com/Prakxo/ac-decomp/blob/master/src/m_timeIn_ovl.c

But yeah there're still a lot of other constraints preventing us from adding something like that. The biggest is that the luni-solar based events cannot be algorithmically calculated due to how it works. You can approximate the dates but it's not going to be exact unless you hardcode them. So we would either have to ditch luni-solar event calendar or add in N years we want to support.

**Comment by TheSystemGuy1337** [comment] 2024-01-07 05:05
> > The repo can't currently achieve that yet, since the timein submenú overlay (aka the date changer before loading your player) isn't implemented yet, and other changes in the repo too that clamp the year to 2030
> > Regardless anything, I think it would be good to do that whenever it's done, but at the moment it's not possible with the decomp at this current state
> 
> `m_timeIn_ovl` is linked, https://github.com/Prakxo/ac-decomp/blob/master/src/m_timeIn_ovl.c
> 
> But yeah there're still a lot of other constraints preventing us from adding something like that. The biggest is that the luni-solar based events cannot be algorithmically calculated due to how the calendar works. You can approximate the dates but it's not going to be exact unless you hardcode them. So we would either have to ditch the luni-solar event calendar or add in N years we want to support.

The best solution is to hardcode 2099 as the date rather than removing it. Besides, 2099 is the maximum value that the GameCube's internal real-time clock will accept. This has the bonus of preventing people from jumping on the fear bandwagon and [selling $40 survival kits](https://www.youtube.com/watch?v=kxPHMi8YxTg)

**Comment by Cuyler36** [comment] 2024-01-07 05:11
This will be considered but in a mod repo. The 2030 year limit is not a bug. The only optional features added to this decomp repo at the moment are bugfixes and minor code flow improvements. I will be increasing the maximum year to 2100 in my 'deluxe' mod but that's separate from decomp.

https://github.com/Cuyler36/ac-decomp/tree/deluxe

**Closed by Cuyler36** 2024-01-07 05:11 UTC

**Comment by TheSystemGuy1337** [comment] 2024-01-07 05:22
> This will be considered but in a mod repo. The 2030 year limit is not a bug. The only optional features added to this decomp repo at the moment are bugfixes and minor code flow improvements. I will be increasing the maximum year to 2100 in my 'deluxe' mod but that's separate from decomp.
> 
> https://github.com/Cuyler36/ac-decomp/tree/deluxe

Still better than no bugfix at all. And having to worry about people trying to leverage this for monetary gain

**Comment by MisterSheeple** [comment] 2024-01-07 06:18
> Still better than no bugfix at all. And having to worry about people trying to leverage this for monetary gain

The thing is it's not necessarily a bug. The devs intended it to go through 2030. Optional bug fixes are only present for mistakes made by the devs, such as oranges being unobtainable in your town unless you have peaches. As for someone leveraging it for monetary gain, I don't think you have to worry about that. Nothing like that has happened for other decomp projects like Super Mario 64, Zelda OoT, etc.

**Comment by TheSystemGuy1337** [comment] 2024-01-07 13:16
So it really isn’t a bug, rather it was done to make programming easy and to save a dozen bytes of memory. This really looks like Y2K to me. Also, by people leveraging it for monetary gain; I mean fear mongers leveraging the fact the game only goes up to 2030 and trying to sell $40 “survival kits” much like they did in the late 90s when Y2K was near. Nintendo’s programmers should have had a little bit more foresight about that, as tons of people still play the original Animal Crossing and most GameCubes are still working nearly 20 years later.

**Comment by brannanz** [comment] 2024-01-17 18:01
tbf no programmer for a game 20 years ago would have expected people to still be playing 2 decades later
